In [2]:
import pandas as pd

In [3]:
questions_df = pd.read_csv("../data/symptom_questions.csv")
questions_df.head()

,symptom_id,symptom_category,question,answer_type
0,S1,Visual,Has the lesion changed in color?,binary
1,S2,Visual,Is the lesion asymmetrical?,binary
2,S3,Visual,Are the borders irregular or uneven?,binary
3,S4,Visual,Has the lesion increased in size recently?,binary
4,S5,Visual,Is there any open sore or ulcer?,binary

In [4]:
questions_df.columns, len(questions_df)

(Index(['symptom_id', 'symptom_category', 'question', 'answer_type'], dtype='str'),
 19)

In [5]:
disease_symptom_df = pd.read_csv("../data/disease_symptom_matrix.csv")
disease_symptom_df.head()

,disease,S1,S2,S3,S4,S5,S6,S7,S8,S9,S10,S11,S12,S13,S14,S15,S16,S17,S18,S19
0,mel,1.0,1.0,1.0,1.0,0.5,0.5,0,0,0,0.5,0.5,0,1.0,0,0.5,1,0.5,1.0,1
1,bcc,1.0,0.5,0.5,1.0,1.0,1.0,1,0,1,0.0,0.5,0,0.5,0,1.0,1,1.0,0.5,0
2,akiec,0.5,0.0,0.0,0.5,0.0,0.0,1,1,0,0.5,0.0,0,0.0,1,0.0,1,1.0,0.0,0
3,bkl,0.5,0.0,0.0,0.0,0.0,0.0,1,1,0,0.0,0.0,0,0.0,1,0.0,0,1.0,0.0,0
4,nv,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0.0,0.0,0,0.0,1,0.0,0,0.0,0.0,0

In [6]:
disease_symptom_df.columns, disease_symptom_df.shape

(Index(['disease', 'S1', 'S2', 'S3', 'S4', 'S5', 'S6', 'S7', 'S8', 'S9', 'S10',
        'S11', 'S12', 'S13', 'S14', 'S15', 'S16', 'S17', 'S18', 'S19'],
       dtype='str'),
 (7, 20))

In [7]:
disease_symptom_df.head()

,disease,S1,S2,S3,S4,S5,S6,S7,S8,S9,S10,S11,S12,S13,S14,S15,S16,S17,S18,S19
0,mel,1.0,1.0,1.0,1.0,0.5,0.5,0,0,0,0.5,0.5,0,1.0,0,0.5,1,0.5,1.0,1
1,bcc,1.0,0.5,0.5,1.0,1.0,1.0,1,0,1,0.0,0.5,0,0.5,0,1.0,1,1.0,0.5,0
2,akiec,0.5,0.0,0.0,0.5,0.0,0.0,1,1,0,0.5,0.0,0,0.0,1,0.0,1,1.0,0.0,0
3,bkl,0.5,0.0,0.0,0.0,0.0,0.0,1,1,0,0.0,0.0,0,0.0,1,0.0,0,1.0,0.0,0
4,nv,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0.0,0.0,0,0.0,1,0.0,0,0.0,0.0,0

In [8]:
# Case 1: diseases are rows
disease_names = disease_symptom_df.iloc[:, 0].tolist()

disease_names

['mel', 'bcc', 'akiec', 'bkl', 'nv', 'df', 'vasc']

In [9]:
symptom_names = disease_symptom_df.columns[1:].tolist()
len(symptom_names), symptom_names[:5]

(19, ['S1', 'S2', 'S3', 'S4', 'S5'])

In [10]:
disease_to_symptoms = {}

for _, row in disease_symptom_df.iterrows():
    disease = row.iloc[0]
    relevant_symptoms = []

    for symptom in symptom_names:
        if row[symptom] == 1:
            relevant_symptoms.append(symptom)

    disease_to_symptoms[disease] = relevant_symptoms

disease_to_symptoms

{'mel': ['S1', 'S2', 'S3', 'S4', 'S13', 'S16', 'S18', 'S19'],
 'bcc': ['S1', 'S4', 'S5', 'S6', 'S7', 'S9', 'S15', 'S16', 'S17'],
 'akiec': ['S7', 'S8', 'S14', 'S16', 'S17'],
 'bkl': ['S7', 'S8', 'S14', 'S17'],
 'nv': ['S14'],
 'df': ['S12', 'S14'],
 'vasc': ['S1', 'S6', 'S14']}

In [11]:
questions_df.columns

Index(['symptom_id', 'symptom_category', 'question', 'answer_type'], dtype='str')

In [12]:
questions_df.head(1)

  symptom_id symptom_category                          question answer_type
0         S1           Visual  Has the lesion changed in color?      binary

In [13]:
symptom_id_to_questions = {}

for _, row in questions_df.iterrows():
    symptom_id = row['symptom_id']
    question_text = row['question']

    if symptom_id not in symptom_id_to_questions:
        symptom_id_to_questions[symptom_id] = []

    symptom_id_to_questions[symptom_id].append(question_text)

list(symptom_id_to_questions.items())[:3]

[('S1', ['Has the lesion changed in color?']),
 ('S2', ['Is the lesion asymmetrical?']),
 ('S3', ['Are the borders irregular or uneven?'])]

In [14]:
disease_to_symptoms

{'mel': ['S1', 'S2', 'S3', 'S4', 'S13', 'S16', 'S18', 'S19'],
 'bcc': ['S1', 'S4', 'S5', 'S6', 'S7', 'S9', 'S15', 'S16', 'S17'],
 'akiec': ['S7', 'S8', 'S14', 'S16', 'S17'],
 'bkl': ['S7', 'S8', 'S14', 'S17'],
 'nv': ['S14'],
 'df': ['S12', 'S14'],
 'vasc': ['S1', 'S6', 'S14']}

In [24]:
def get_questions_for_disease(disease, max_questions=3):
    symptom_ids = disease_to_symptoms.get(disease, [])
    selected_questions = []

    for sid in symptom_ids:
        if sid in symptom_id_to_questions:
            selected_questions.extend(symptom_id_to_questions[sid])

        if len(selected_questions) >= max_questions:
            break

    return selected_questions[:max_questions]

In [25]:
test_disease = 'mel'   # example
questions = get_questions_for_disease(test_disease)

print("Disease:", test_disease)
for q in questions:
    print("-", q)

Disease: mel
- Has the lesion changed in color?
- Is the lesion asymmetrical?
- Are the borders irregular or uneven?

In [26]:
ANSWER_SPACE = ["YES", "NO", "UNKNOWN"]

In [27]:
def initialize_answer_store(questions):
    return {q: None for q in questions}

In [28]:
answer_store = initialize_answer_store(questions)
answer_store

{'Has the lesion changed in color?': None,
 'Is the lesion asymmetrical?': None,
 'Are the borders irregular or uneven?': None}

In [29]:
# Simulated user responses (temporary)
answer_store['Has the lesion changed in color?'] = "YES"
answer_store['Is the lesion asymmetrical?'] = "YES"
answer_store['Are the borders irregular or uneven?'] = "NO"

answer_store

{'Has the lesion changed in color?': 'YES',
 'Is the lesion asymmetrical?': 'YES',
 'Are the borders irregular or uneven?': 'NO'}

In [30]:
question_to_symptom_id = {}

for _, row in questions_df.iterrows():
    question_to_symptom_id[row['question']] = row['symptom_id']

list(question_to_symptom_id.items())[:3]

[('Has the lesion changed in color?', 'S1'),
 ('Is the lesion asymmetrical?', 'S2'),
 ('Are the borders irregular or uneven?', 'S3')]

In [31]:
def build_symptom_evidence(answer_store):
    symptom_evidence = {}

    for question, answer in answer_store.items():
        symptom_id = question_to_symptom_id.get(question)

        if symptom_id is None:
            continue

        symptom_evidence[symptom_id] = answer

    return symptom_evidence

In [32]:
symptom_evidence = build_symptom_evidence(answer_store)
symptom_evidence

{'S1': 'YES', 'S2': 'YES', 'S3': 'NO'}

In [33]:
SYMPTOM_ANSWER_WEIGHT = {
    "YES": 1.0,
    "NO": -0.5,
    "UNKNOWN": 0.0
}

In [34]:
def compute_symptom_support(symptom_evidence):
    score = 0.0
    for answer in symptom_evidence.values():
        score += SYMPTOM_ANSWER_WEIGHT.get(answer, 0.0)
    return score

In [35]:
symptom_support_score = compute_symptom_support(symptom_evidence)
symptom_support_score

1.5

In [36]:
def normalize_symptom_score(score, max_possible=3.0):
    normalized = score / max_possible
    return max(-1.0, min(1.0, normalized))

In [37]:
def fuse_confidence(image_confidence, symptom_score, alpha=0.7):
    symptom_signal = normalize_symptom_score(symptom_score)
    fused = (alpha * image_confidence) + ((1 - alpha) * (image_confidence + symptom_signal * 0.2))
    return max(0.0, min(1.0, fused))

In [38]:
image_confidence = 0.31  # simulated CNN confidence

fused_confidence = fuse_confidence(
    image_confidence,
    symptom_support_score
)

print("Image confidence :", round(image_confidence, 2))
print("Symptom score    :", symptom_support_score)
print("Fused confidence :", round(fused_confidence, 2))

Image confidence : 0.31
Symptom score    : 1.5
Fused confidence : 0.34

In [39]:
HIGH_CONF_THRESHOLD = 0.70
MID_CONF_THRESHOLD  = 0.40
LOW_CONF_THRESHOLD  = 0.25

In [40]:
def decide_action(confidence):
    if confidence >= HIGH_CONF_THRESHOLD:
        return "SAFE_ADVISORY"
    elif confidence >= MID_CONF_THRESHOLD:
        return "ASK_MORE_QUESTIONS"
    elif confidence >= LOW_CONF_THRESHOLD:
        return "LOW_CONFIDENCE_WARNING"
    else:
        return "ETHICAL_REFUSAL"

In [41]:
initial_action = decide_action(image_confidence)
final_action   = decide_action(fused_confidence)

print("Initial image confidence :", round(image_confidence, 2))
print("Initial decision         :", initial_action)
print("Fused confidence         :", round(fused_confidence, 2))
print("Final decision           :", final_action)

Initial image confidence : 0.31
Initial decision         : LOW_CONFIDENCE_WARNING
Fused confidence         : 0.34
Final decision           : LOW_CONFIDENCE_WARNING